[project]
name = "gke-terraform"
version = "0.1.0"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
gke-terraform = { path = ".", editable = true }

[tool.pixi.dependencies]
terraform = ">=1.8.1,<1.9"
